### ISSUE TITLE
Upload failure on latest Mono.

### ISSUE THREAD

**Issue by paulduchesne** [Kompakkt/Kompakkt#9]
### What

Failure to upload models, upload button greyed out, errors to console and server. Data appears to be written to Mongo, but issue moving the files into the "uploads" directory? Testing commit history shows the issue being introduced on Repo commit `3888fc2df74bdf68f827607c0dcaeadb4a8c8975`

### Where

Issue occurs when running Kompakkt-Mono with default config.

### Screenshot

![kompakkt-upload-error](https://user-images.githubusercontent.com/45246635/190128525-3d934b51-67ca-4068-bbb8-a648e15fc5ab.png)

### Console Output

```
User karelle logged in
 [SERVER]  SyntaxError: Unexpected token - in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/home/paulduchesne/git/cologne-mono/Server/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/home/paulduchesne/git/cologne-mono/Server/node_modules/body-parser/lib/types/json.js:83:15)
    at /home/paulduchesne/git/cologne-mono/Server/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/home/paulduchesne/git/cologne-mono/Server/node_modules/raw-body/index.js:224:16)
    at done (/home/paulduchesne/git/cologne-mono/Server/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/paulduchesne/git/cologne-mono/Server/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
 [SERVER]  [INFO|2022-09-14T10:17:44.618Z]
{ uuid: '6321aa3a3a811203739ea4c4', type: 'model' }
 [SERVER]  [ERR|2022-09-14T10:17:44.627Z]
Error: 
    at Object.err (/home/paulduchesne/git/cologne-mono/Server/src/services/logger.ts:77:18)
    at /home/paulduchesne/git/cologne-mono/Server/src/services/upload.ts:163:14
Error: ENOENT: no such file or directory, scandir '/home/paulduchesne/git/cologne-mono/Server/src/uploads/model/6321aa3a3a811203739ea4c4'
    at Object.readdirSync (fs.js:1043:3)
    at Object.klawSync [as default] (/home/paulduchesne/git/cologne-mono/Server/node_modules/klaw-sync/klaw-sync.js:13:25)
    at /home/paulduchesne/git/cologne-mono/Server/src/services/upload.ts:117:34 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/paulduchesne/git/cologne-mono/Server/src/uploads/model/6321aa3a3a811203739ea4c4'
}

```

**Comment by HeyItsBATMAN** [comment]
Thanks for reporting the issue. Should be fixed by https://github.com/Kompakkt/Repo/commit/40c2a5679c9899b751f573440d03d8416484da66
